Document = Definition+ <whitespace?>
CommentChar = <whitespace?> #"[\x{9}\x{20}-\uFFFF]"
FloatValue = IntegerPart FractionalPart
EnumValue = Name
ListValue = <whitespace?> "[" <whitespace?> "]" | <whitespace?> "[" Value <whitespace?> "]"
Sign = <whitespace?> "+" | <whitespace?> "-"
IntValue = IntegerPart
<whitespace> = #"\s+"
ExponentIndicator = <whitespace?> "e" | <whitespace?> "E"
Token = Punctuator | Name | IntValue | FloatValue | StringValue
Comment = <whitespace?> "#" CommentChar+
Field = Alias? Name Arguments? Directives? SelectionSet?
VariableDefinitions = <whitespace?> "(" VariableDefinition+ <whitespace?> ")"
FragmentName = Name
IntegerPart = NegativeSign? <whitespace?> "0" | NegativeSign? NonZeroDigit Digit*
Ignored = <whitespace?> #"\s+" | Comment | Comma
EscapedCharacter = <whitespace?> "\\" <whitespace?> #"[\"\/bfnrt]"
LineTerminator = <whitespace?> #"\x{A}" | <whitespace?> #"\x{D}\x{A}" | <whitespace?> #"\x{D}"
StringValue = <whitespace?> "\"" <whitespace?> "\"" | <whitespace?> "\"" StringCharacter+ <whitespace?> "\""
Directive = <whitespace?> "@" Name Arguments?
BooleanValue = <whitespace?> "true" | <whitespace?> "false"
InlineFragment = <whitespace?> "..." TypeCondition? Directives? SelectionSet
FragmentSpread = <whitespace?> "..." FragmentName Directives?
SourceCharacter = <whitespace?> #"[\x{9}\x{A}\x{D}\x{20}-\uFFFF]"
NonNullType = NamedType | ListType
Punctuator = <whitespace?> #"[!$().:=@\[\]\{\}]"
Definition = OperationDefinition FragmentDefinition
TypeCondition = <whitespace?> "on" NamedType
Arguments = <whitespace?> "(" Argument+ <whitespace?> ")"
ListType = <whitespace?> "[" Type <whitespace?> "]"
Directives = Directive+
NonZeroDigit = <whitespace?> "[1-9]"
NegativeSign = <whitespace?> "-"
Comma = <whitespace?> ","
NamedType = Name
StringCharacter = <whitespace?> #"[\x{9}\x{20}-\x{49}\x{51}-\uFFFF]" | <whitespace?> "\\" <whitespace?> "u" EscapedUnicode | <whitespace?> "\\" EscapedCharacter
EscapedUnicode = <whitespace?> #"[0-9A-Fa-f]{4}"
Variable = <whitespace?> "$" Name
Value = Variable | IntValue | FloatValue | StringValue | BooleanValue | EnumValue | ListValue | ObjectValue
ExponentPart = ExponentIndicator Sign? Digit+
Name = <whitespace?> #"[_A-Za-z][_0-9A-Za-z]*"
ObjectField = Name <whitespace?> ":" Value
DefaultValue = Value
Type = NamedType | ListType | NonNullType
Selection = Field | FragmentSpread | InlineFragment
UnicodeBOM = <whitespace?> "﻿"
Argument = Name <whitespace?> ":" Value
Alias = Name <whitespace?> ":"
OperationType = <whitespace?> "query" | <whitespace?> "mutation"
ObjectValue = <whitespace?> "{" <whitespace?> "}" | <whitespace?> "{" ObjectField <whitespace?> "}"
Digit = <whitespace?> "[0-9]"
OperationDefinition = OperationType Name? VariableDefinitions? Directives? SelectionSet
FractionalPart = <whitespace?> "." Digit+
FragmentDefinition = <whitespace?> "fragment" FragmentName TypeCondition Directives? SelectionSet
VariableDefinition = <whitespace?> "(" VariableDefinition <whitespace?> ")" | Variable <whitespace?> ":" Type DefaultValue?
SelectionSet = <whitespace?> "{" Selection <whitespace?> "}"
WhiteSpace = <whitespace?> #"[\x{9}\x{20}]+"
