Document ::= Definition+
Definition ::= OperationDefinition FragmentDefinition
OperationDefinition ::= OperationType Name? VariableDefinitions? Directives? SelectionSet
OperationType ::= "query" | "mutation"
VariableDefinitions ::= "(" VariableDefinition+ ")"
SourceCharacter ::= #"[\x{9}\x{A}\x{D}\x{20}-\uFFFF]"
UnicodeBOM ::= "\uFEFF"
WhiteSpace ::= #"[\x{9}\x{20}]"
LineTerminator ::= #"\x{A}" | #"\x{D}\x{A}" | #"\x{D}"
CommentChar ::= #"[\x{9}\x{20}-\uFFFF]"
Comment ::= CommentChar+
Comma ::= ","
Punctuator ::= #"[!$().:=@\[\]\{\}]"
Name ::= #"[_A-Za-z][_0-9A-Za-z]"
NegativeSign ::= "-"
NonZeroDigit ::= "[1-9]"
Digit ::= "[0-9]"
IntegerPart ::= NegativeSign? '0' | NegativeSign? NonZeroDigit Digit*
IntValue ::= IntegerPart
FractionalPart ::= "." Digit+
ExponentIndicator ::= "e" | "E"
Sign ::= "+" | "-"
ExponentPart ::= ExponentIndicator Sign? Digit+
FloatValue ::= IntegerPart FractionalPart
EscapedUnicode ::= #"[0-9A-Fa-f]{4}"
EscapedCharacter ::= "\\" #"[\"\/bfnrt]"
StringCharacter ::= #"[\x{9}\x{20}-\x{49}\x{51}-\uFFFF]" | "\\" "u" EscapedUnicode | "\\" EscapedCharacter
StringValue ::=  "\"""\"" | "\"" StringCharacter+ "\""
Token ::= Punctuator | Name | IntValue | FloatValue | StringValue
EnumValue ::= Name
Value ::= Variable | IntValue | FloatValue | StringValue | BooleanValue | EnumValue | ListValue | ObjectValue
Variable ::= "$" Name
VariableDefinition ::= "(" VariableDefinition ")" | Type DefaultValue?
Type ::= NamedType | ListType | NonNullType
NamedType ::= Name
ListType ::= "[" Type "]"
NonNullType ::= NamedType | ListType
DefaultValue ::= Value
BooleanValue ::= "true" | "false"
ObjectValue ::= "{" "}" | "{" ObjectField "}"
ObjectField ::= Name ":" Value
ListValue ::= "[" "]" | "[" Value "]"
Directives ::= Directive+
Directive ::= "@" Name Arguments?
Arguments ::= "(" Argument+ ")"
Argument ::= Name ":" Value
Alias ::= Name ":"
FragmentSpread ::= "..." FragmentName Directives?
FragmentDefinition ::= "fragment" FragmentName TypeCondition Directives? SelectionSet
FragmentName ::= Name
TypeCondition ::= "on" NamedType
SelectionSet ::= "{" Selection+ "}"
Selection ::= Field | FragmentSpread | InlineFragment
Field ::= Alias? Name Arguments? Directives? SelectionSet?
InlineFragment ::= "..." TypeCondition? Directives? SelectionSet
